spin_settings.admin_settings_form:
  path: '/admin/config/spectrum'
  defaults:
    _form: '\Drupal\spectrum_settings\Form\SpectrumSettingsForm'
    _title: 'Spectrum settings'
  requirements:
    _permission: 'administer spectrum settings'
