services:
    core.security.jwt_manager:
        class: App\CoreBundle\Security\JWT\FirebaseJWTManager
        arguments:
            - '%secret%'

    app_core.admin.form_data:
        class: App\CoreBundle\Admin\FormDataAdmin
        arguments: [~, App\CoreBundle\Entity\FormData, AppCoreBundle:FormDataAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: FormData }

    app.elastica.model.transformer:
            class: App\CoreBundle\Elastica\ElasticaToModelTransformer
            calls:
                - [ setPropertyAccessor, ["@fos_elastica.property_accessor"] ]
            tags:
                - { name: fos_elastica.elastica_to_model_transformer.app.company }

    app.search.repository.base:
        class: App\CoreBundle\Elastica\Repository\BaseRepository


    app.search.repository.page:
        class: App\CoreBundle\Elastica\Repository\PageRepository

    app.search.repository.page_crawled:
        class: App\CoreBundle\Elastica\Repository\PageCrawledRepository

    app.search.repository.tag:
        class: App\CoreBundle\Elastica\Repository\TagRepository

    app.search.repository.tab_page:
        class: App\CoreBundle\Elastica\Repository\TabPageRepository