sonata_page:
    multisite: host
    use_streamed_response: true # set the value to false in debug mode or if the reverse proxy does not handle streamed response
    ignore_route_patterns:
        - ^_(.*)          # ignore symfony routes
        - ^(.*)admin(.*)   # ignore admin route, ie route containing 'admin'
        - ^(.*)front_end_(.*)
        - ^(.*)api_(.*)

    ignore_routes:
        - sonata_page_esi_cache
        - sonata_page_ssi_cache
        - sonata_page_js_sync_cache
        - sonata_page_js_async_cache
        - sonata_cache_esi
        - sonata_cache_ssi
        - sonata_cache_js_async
        - sonata_cache_js_sync
        - sonata_cache_apc

    ignore_uri_patterns:
        - ^/%admin_directory%(.*)
        - ^/api(.*)

    page_defaults:
        homepage: {decorate: false} # disable decoration for homepage, key - is a page route

    default_template: default
    direct_publication: true
    templates:
        default:
            name: 'Default'
            path: 'ApplicationSonataPageBundle::default_layout.html.twig'
            containers:
                content:
                    name: Main
                    #blocks:
                    #    - app.block.service.text
                    #    - app.block.service.chat_live_side
            matrix:
                layout: |

                    CCCCCCCC

                mapping:
                  C: content

    # manage the http errors
    catch_exceptions:
        not_found: []    # render 404 page with "not_found" key (name generated: _page_internal_error_{key})
        fatal:     []    # so you can use the same page for different http errors or specify specific page for each error