version: '2'
services:
    frontend:
        build: ./frontend
        image: spectrum/frontend
        volumes:
            - ../../:/app
    backend:
        image: wodby/drupal-php:7.1
        command: sh
        volumes:
            - '../../source/drupal:/app'
