imports:
    - { resource: parameters.yml }
    - { resource: doctrine/config.yml }
    - { resource: sonata/config.yml }
    - { resource: fos/config.yml }
    - { resource: security.yml }
    - { resource: services.yml }

framework:
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: false
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        handler_id:  session.handler.pdo
    fragments:       ~
    http_method_override: true

twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        env: %kernel.environment%
        asset_version: %asset_version%
    paths:
       "%kernel.root_dir%/../src/App/ApiBundle/Resources/views/templates": ApiBundleTemplate
    form:
        resources: ['bootstrap_3_layout.html.twig']


swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

nelmio_api_doc: ~

doctrine:
    orm:
        entity_managers:
            default:
                mappings:

    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType

exercise_html_purifier:
    crawler:
        HTML.AllowedElements: [h1, h2, h3, h4, h5, h6, p, br, strong, ul, ol, li, img, a]
        HTML.AllowedAttributes: ["img.src", "img.alt", "img.title", "a.href", "a.title"]
        AutoFormat.RemoveEmpty: true
        AutoFormat.RemoveEmpty.RemoveNbsp: true
        Output.Newline: "\n"