parameters:
    database_driver: pdo_mysql
    database_host: rd1498as9tagu00.cydgm36eaxsm.us-east-1.rds.amazonaws.com
    database_port: 3306
    database_name: rebuusuat
    database_user: rebuusuat
    database_password: V9ZScd6sT3N0m8DE1dRb8objzWKuz2wE

    aws_s3_key: AKIAJ66FBQNRZICSR4NQ
    aws_s3_secret: 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
    aws_s3_bucket: mediamonks-development
    aws_s3_region: us-west-1