parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: 3306
    database_name: spectrumreach
    database_user: root
    database_password:

    aws_s3_key: AKIAJ66FBQNRZICSR4NQ
    aws_s3_secret: 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
    aws_s3_bucket: mediamonks-development
    aws_s3_region: us-west-1

    crawler_client: crawler_client_prerender_io

    fos_elastica_servers:
            - {host: localhost, port: 9200}