parameters:
    database_driver: pdo_mysql
    database_host: 	sdih6yua7cto26.cydgm36eaxsm.us-east-1.rds.amazonaws.com
    database_port: 3306
    database_name: spectrumusuat
    database_user: spectrumusuat
    database_password: hzPIhMD2w2wwEhwSSDhULugW4zRfF624