tweets_username: SpectrumReach
access_token: 115780415-ATwFgoQQJ1ZuMZTc2o6qyi1c26ZRxoqNGzn4yV8T
token_secret: 2O8aCancjiNloqVYw10VDWccoWHUOilNgsvay9IKvPTMi
consumer_key: EZcoHZhWFdQeYvOfRX3rHtK0N
consumer_secret: BmOgti77rY0c6vGF5azQCxioevjf7ffUOOxudaef6ZeNMfOIet
